server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/brand?useUnicode=true&useServerPrepStmts=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    username: root  # username can't write name
    password: 123456
    initialSize: 5
    maxActive: 10
    maxWait: 3000

mybatis:
  mapper-locations: classpath:ewk/code19/mapper/*.xml     # mapper